name: CICD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run check

  Deploy:
    runs-on: self-hosted
    needs: Testing
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Install Dependencie
        run: npm install

      - name: the Application By PM2
        run: |
          la-la
          pm2 status
          pm2 delete Server || true
          #pm2 restart all
          pm2 start "npm start" --name="server"
          pm2 save 

